--- 
- hosts: all 
  become: yes 
  tasks: 
    - name: i want to install webserever
      apt: 
        name: "{{myubuntuserver}}"
        state: present
    - name: i want to install tree 
      apt: 
        name: tree 
        state: present 